### PR TITLE
Add `@opentelemetry/api` as peer dependency

### LINKED ISSUE #11: `@open-telemetry/api` should be a peer dependency
In all instrumentations, `@open-telemetry/api` should be a peer dependency. Example: https://github.com/open-telemetry/opentelemetry-js/blob/079c1f547a32b84e775f1df850b8e66f575ed7ca/experimental/packages/opentelemetry-instrumentation-grpc/package.json#L75

### PR DESCRIPTION
**Pull request by satazor**
Closes #11 

PS: I couldn't run `yarn` to update the yarn lock because I'm using yarn v1. Recent versions of yarn give me all sort of problems.

### CODE REVIEW

**Comment by satazor** [comment]
@diogotorres97 fixed it for me, yarn.lock is updated

**Comment by diogotorres97** [comment]
@djMax @mydea @chentsulin ^^ 🙏

**Comment by diogotorres97** [comment]
any news here?

**Review by diogotorres97 — APPROVED** [review]

**Comment by diogotorres97** [comment]
@djMax @mydea @chentsulin ping 😢

**Review by djMax — APPROVED** [review]

**Pull request merged**
